/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openfoods.configs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hornellama
 */
public class SQLDB {
    private Connection cnx;
    private Statement st;
    private ResultSet rowsResultSet;
    private String query;
    private IAsyncQuery iAsyncQuery;
    public SQLDB() throws ClassNotFoundException, SQLException{
        try{
             Class.forName("com.mysql.jdbc.Driver");
        cnx=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_resto_backup?autoReconnect=true&useSSL=false","openfoods","");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
       
    }
    public void setQuery(String sqlQuery,IAsyncQuery iAsyncQuery) throws SQLException{
        this.query=sqlQuery;
        this.iAsyncQuery=iAsyncQuery;
        
        st=cnx.createStatement();
        rowsResultSet=st.executeQuery(sqlQuery);
        iAsyncQuery.getResult(rowsResultSet);
    }
    public int setQueryUpdate(String sqlQuery) throws SQLException{
        int autogeneratedKeys=0;
        this.query=sqlQuery;
        this.iAsyncQuery=iAsyncQuery;
        st=cnx.createStatement();
        st.executeUpdate(sqlQuery, Statement.RETURN_GENERATED_KEYS);
        rowsResultSet=st.getGeneratedKeys();
        while(rowsResultSet.next()){
            autogeneratedKeys=rowsResultSet.getInt(1);
        }
        return autogeneratedKeys;
    }
    public Connection getConnection(){
        return this.cnx;
    }
    
    
}
